/* =========================================================
   TechStore — CATÁLOGO
   ---------------------------------------------------------
   Cada producto:
     id       identificador único (sin espacios)
     cat      celulares | consolas | retro | mouse | teclados | audio
     brand    marca
     name     nombre corto que se muestra en la tarjeta
     title    título completo (opcional)
     price    precio actual en MXN (con IVA)
     old      precio anterior tachado (opcional)
     img      foto principal (carpeta img/)
     badge    etiqueta opcional ("Nuevo", "Recertificado"…)
     soldOut  true = se muestra "Agotado" y el botón pregunta por WhatsApp (opcional)
     featured true = aparece en "Ofertas destacadas"
     desc     descripción
     hl       puntos clave
     specs    tabla de especificaciones [etiqueta, valor]
     options  variantes. Cada valor puede tener:
                available:false  -> se muestra tachado (agotado)
                price / old      -> precio propio de esa variante
                img              -> foto de esa variante
                hex              -> color de la muestra
   ========================================================= */

const CATEGORIES = [
  { id: "celulares", label: "Celulares", icon: "phone", blurb: "iPhone y Samsung Galaxy" },
  { id: "consolas", label: "Consolas", icon: "gamepad", blurb: "Nintendo, PlayStation y Xbox" },
  { id: "retro", label: "Retro", icon: "joystick", blurb: "Clásicos listos para tu TV" },
  { id: "mouse", label: "Mouse", icon: "mouse", blurb: "Precisión para cada estilo" },
  { id: "teclados", label: "Teclados", icon: "keyboard", blurb: "Mecánicos, kits y RGB" },
  { id: "audio", label: "Audífonos", icon: "headphones", blurb: "Diadema y true wireless" },
];

/* ---------- Celulares: estado, capacidad y color ---------- */
const SEMI_NUEVO_NOTE =
  "Equipo semi nuevo: revisado, funcional y en excelente estado estético. Outlet: equipo en perfecto funcionamiento que puede mostrar ligeras marcas de uso.";

const phone = (p) => ({
  cat: "celulares",
  brand: "Apple",
  badge: "Oferta",
  ...p,
  options: [
    { key: "estado", label: "Estado", values: p.conditions },
    { key: "capacidad", label: "Capacidad", values: p.storage },
    { key: "color", label: "Color", type: "swatch", values: p.colors },
  ],
});

const galaxy = (p) =>
  phone({
    brand: "Samsung",
    badge: p.old ? "Oferta" : undefined,
    ...p,
    desc: p.desc + " " + SEMI_NUEVO_NOTE,
  });

const PRODUCTS = [
  /* ===================== CELULARES ===================== */
  phone({
    id: "iphone-16-pro-max",
    name: "iPhone 16 Pro Max",
    price: 20240,
    old: 28540,
    img: "img/p50.jpg",
    featured: true,
    desc: "La pantalla más grande de la familia iPhone 16 con chip A18 Pro, estructura de titanio y el sistema de cámaras Pro con teleobjetivo 5x. " + SEMI_NUEVO_NOTE,
    hl: ["Pantalla Super Retina XDR de 6.9\"", "Chip A18 Pro", "Cámara Fusion de 48 MP + teleobjetivo 5x", "Diseño de titanio", "Control de la Cámara y botón de Acción"],
    specs: [["Pantalla", "6.9\" Super Retina XDR, ProMotion"], ["Chip", "A18 Pro"], ["Cámaras", "48 MP Fusion · 48 MP ultra gran angular · 12 MP teleobjetivo 5x"], ["Material", "Titanio"], ["Conector", "USB-C"], ["Red", "5G"]],
    conditions: [{ label: "Outlet" }, { label: "Semi nuevo" }],
    storage: [{ label: "256GB" }, { label: "512GB" }, { label: "1TB" }],
    colors: [
      { label: "Titanio negro", hex: "#3c3c3d", img: "img/p68.jpg" },
      { label: "Titanio blanco", hex: "#ecebe7", img: "img/p50.jpg" },
      { label: "Titanio desierto", hex: "#c9b39b", img: "img/p51.jpg" },
      { label: "Titanio natural", hex: "#bdb8b0", img: "img/p52.jpg" },
      { label: "Titanio azul", hex: "#3f4a5c", img: "img/p53.jpg" },
    ],
  }),
  phone({
    id: "iphone-16-pro",
    name: "iPhone 16 Pro",
    price: 18290,
    old: 25590,
    img: "img/p68.jpg",
    featured: true,
    desc: "Potencia Pro en un tamaño cómodo: chip A18 Pro, titanio y triple cámara con teleobjetivo 5x. " + SEMI_NUEVO_NOTE,
    hl: ["Pantalla Super Retina XDR de 6.3\"", "Chip A18 Pro", "Teleobjetivo 5x", "Diseño de titanio", "USB-C"],
    specs: [["Pantalla", "6.3\" Super Retina XDR, ProMotion"], ["Chip", "A18 Pro"], ["Cámaras", "48 MP Fusion · 48 MP ultra gran angular · 12 MP teleobjetivo 5x"], ["Material", "Titanio"], ["Conector", "USB-C"], ["Red", "5G"]],
    conditions: [{ label: "Outlet" }, { label: "Semi nuevo" }],
    storage: [{ label: "128GB" }, { label: "256GB" }, { label: "512GB" }, { label: "1TB" }],
    colors: [
      { label: "Titanio negro", hex: "#3c3c3d", img: "img/p68.jpg" },
      { label: "Titanio blanco", hex: "#ecebe7", img: "img/p50.jpg" },
      { label: "Titanio desierto", hex: "#c9b39b", img: "img/p51.jpg" },
      { label: "Titanio natural", hex: "#bdb8b0", img: "img/p52.jpg" },
      { label: "Titanio azul", hex: "#3f4a5c", img: "img/p53.jpg" },
    ],
  }),
  phone({
    id: "iphone-air",
    name: "iPhone Air",
    price: 20990,
    old: 22990,
    img: "img/p74.jpg",
    badge: "Nuevo",
    featured: true,
    desc: "El iPhone más delgado jamás creado, con estructura de titanio, pantalla de 6.5\" y chip A19 Pro. " + SEMI_NUEVO_NOTE,
    hl: ["Diseño ultradelgado de titanio", "Pantalla Super Retina XDR de 6.5\"", "Chip A19 Pro", "Cámara Fusion de 48 MP", "Solo eSIM"],
    specs: [["Pantalla", "6.5\" Super Retina XDR, ProMotion"], ["Chip", "A19 Pro"], ["Cámara", "48 MP Fusion"], ["Material", "Titanio"], ["SIM", "eSIM"], ["Conector", "USB-C"]],
    conditions: [{ label: "Outlet" }, { label: "Semi nuevo" }],
    storage: [{ label: "256GB" }, { label: "512GB" }, { label: "1TB" }],
    colors: [
      { label: "Azul cielo", hex: "#a9cbe6", img: "img/p74.jpg" },
      { label: "Negro espacial", hex: "#2e2e30", img: "img/p73.jpg" },
      { label: "Dorado claro", hex: "#ede3c8", img: "img/p75.jpg" },
      { label: "Blanco nube", hex: "#f2f2f2", img: "img/p76.jpg" },
    ],
  }),
  phone({
    id: "iphone-16-plus",
    name: "iPhone 16 Plus",
    price: 16240,
    old: 21240,
    img: "img/p56.jpg",
    desc: "Pantalla de 6.7\" con chip A18, Control de la Cámara y cámara Fusion de 48 MP con gran duración de batería. " + SEMI_NUEVO_NOTE,
    hl: ["Pantalla Super Retina XDR de 6.7\"", "Chip A18", "Cámara Fusion de 48 MP", "Control de la Cámara", "Botón de Acción"],
    specs: [["Pantalla", "6.7\" Super Retina XDR"], ["Chip", "A18"], ["Cámaras", "48 MP Fusion · 12 MP ultra gran angular"], ["Conector", "USB-C"], ["Red", "5G"]],
    conditions: [{ label: "Outlet" }, { label: "Semi nuevo" }],
    storage: [{ label: "128GB" }, { label: "256GB" }, { label: "512GB" }],
    colors: [
      { label: "Rosa", hex: "#f2c3d3", img: "img/p56.jpg" },
      { label: "Blanco", hex: "#f5f5f5", img: "img/p59.jpg" },
      { label: "Negro", hex: "#3a3a3c", img: "img/p55.jpg" },
      { label: "Verde azulado", hex: "#9fcfcb", img: "img/p57.jpg" },
      { label: "Ultramarino", hex: "#7a8cf0", img: "img/p58.jpg" },
    ],
  }),
  phone({
    id: "iphone-16",
    name: "iPhone 16",
    price: 15240,
    old: 19990,
    img: "img/p58.jpg",
    featured: true,
    desc: "Chip A18, Control de la Cámara, botón de Acción y cámara Fusion de 48 MP en colores intensos. " + SEMI_NUEVO_NOTE,
    hl: ["Pantalla Super Retina XDR de 6.1\"", "Chip A18", "Cámara Fusion de 48 MP", "Control de la Cámara", "Botón de Acción"],
    specs: [["Pantalla", "6.1\" Super Retina XDR"], ["Chip", "A18"], ["Cámaras", "48 MP Fusion · 12 MP ultra gran angular"], ["Conector", "USB-C"], ["Red", "5G"]],
    conditions: [{ label: "Outlet" }, { label: "Semi nuevo" }],
    storage: [{ label: "128GB" }, { label: "256GB" }, { label: "512GB" }],
    colors: [
      { label: "Ultramarino", hex: "#7a8cf0", img: "img/p58.jpg" },
      { label: "Blanco", hex: "#f5f5f5", img: "img/p59.jpg" },
      { label: "Negro", hex: "#3a3a3c", img: "img/p55.jpg" },
      { label: "Rosa", hex: "#f2c3d3", img: "img/p56.jpg" },
      { label: "Verde azulado", hex: "#9fcfcb", img: "img/p57.jpg" },
    ],
  }),
  phone({
    id: "iphone-16e",
    name: "iPhone 16e",
    price: 11190,
    old: 14190,
    img: "img/p79.jpg",
    desc: "Lo esencial del iPhone 16 con chip A18, cámara Fusion de 48 MP y Face ID, a un precio más accesible. " + SEMI_NUEVO_NOTE,
    hl: ["Pantalla Super Retina XDR de 6.1\"", "Chip A18", "Cámara Fusion de 48 MP", "Botón de Acción", "USB-C"],
    specs: [["Pantalla", "6.1\" Super Retina XDR"], ["Chip", "A18"], ["Cámara", "48 MP Fusion"], ["Desbloqueo", "Face ID"], ["Conector", "USB-C"]],
    conditions: [{ label: "Outlet" }, { label: "Semi nuevo" }],
    storage: [{ label: "128GB" }, { label: "256GB" }, { label: "512GB" }],
    colors: [
      { label: "Negro", hex: "#1c1c1e", img: "img/p79.jpg" },
      { label: "Blanco", hex: "#f5f5f5", img: "img/p78.jpg" },
    ],
  }),
  phone({
    id: "iphone-15",
    name: "iPhone 15",
    price: 8490,
    old: 9290,
    img: "img/p84.jpg",
    badge: "Súper oferta",
    featured: true,
    desc: "Dynamic Island, cámara principal de 48 MP, chip A16 Bionic y conector USB-C en un acabado de vidrio con color. " + SEMI_NUEVO_NOTE,
    hl: ["Pantalla Super Retina XDR de 6.1\"", "Dynamic Island", "Chip A16 Bionic", "Cámara principal de 48 MP", "USB-C"],
    specs: [["Pantalla", "6.1\" Super Retina XDR"], ["Chip", "A16 Bionic"], ["Cámaras", "48 MP principal · 12 MP ultra gran angular"], ["Conector", "USB-C"], ["Red", "5G"]],
    conditions: [{ label: "Outlet" }, { label: "Semi nuevo" }],
    storage: [{ label: "128GB" }, { label: "256GB" }, { label: "512GB" }],
    colors: [
      { label: "Rosa", hex: "#f6c9d0", img: "img/p84.jpg" },
      { label: "Azul", hex: "#c9dce6", img: "img/p81.jpg" },
      { label: "Negro", hex: "#3a3a3c", img: "img/p82.jpg" },
      { label: "Verde", hex: "#cfe3c8", img: "img/p83.jpg" },
      { label: "Amarillo", hex: "#f5ecb0", img: "img/p85.jpg" },
    ],
  }),
  phone({
    id: "iphone-14",
    name: "iPhone 14",
    price: 6290,
    old: 7990,
    img: "img/p42.jpg",
    desc: "Doble cámara de 12 MP con modo Acción, chip A15 Bionic y gran autonomía en seis colores. " + SEMI_NUEVO_NOTE,
    hl: ["Pantalla Super Retina XDR de 6.1\"", "Chip A15 Bionic", "Doble cámara de 12 MP", "Modo Acción y Cine", "Face ID"],
    specs: [["Pantalla", "6.1\" Super Retina XDR"], ["Chip", "A15 Bionic"], ["Cámaras", "12 MP principal · 12 MP ultra gran angular"], ["Conector", "Lightning"], ["Red", "5G"]],
    conditions: [{ label: "Outlet" }, { label: "Semi nuevo" }],
    storage: [{ label: "128GB" }, { label: "256GB" }, { label: "512GB" }],
    colors: [
      { label: "Azul", hex: "#a9c4dd", img: "img/p42.jpg" },
      { label: "Medianoche", hex: "#2b2f36", img: "img/p43.jpg" },
      { label: "(PRODUCT)RED", hex: "#e1141e", img: "img/p44.jpg" },
      { label: "Blanco estelar", hex: "#f4f0ea", img: "img/p45.jpg" },
      { label: "Morado", hex: "#d9cde6", img: "img/p46.jpg" },
      { label: "Amarillo", hex: "#f9e37a", img: "img/p47.jpg" },
    ],
  }),

  /* ===================== SAMSUNG ===================== */
  galaxy({
    id: "galaxy-s25-plus",
    name: "Samsung Galaxy S25 Plus 5G",
    price: 12743,
    old: 16990,
    img: "img/p249.jpg",
    featured: true,
    desc: "Pantalla QHD+ de 6.7\", Snapdragon 8 Elite for Galaxy y Galaxy AI integrado, con carga súper rápida de 45 W.",
    hl: ["Pantalla Dynamic AMOLED 2X de 6.7\" QHD+", "Snapdragon 8 Elite for Galaxy", "Cámara de 50 MP + teleobjetivo 3x", "Batería de 4,900 mAh", "Galaxy AI"],
    specs: [["Pantalla", "6.7\" Dynamic AMOLED 2X, 120 Hz"], ["Procesador", "Snapdragon 8 Elite for Galaxy"], ["Cámaras", "50 MP · 12 MP ultra gran angular · 10 MP tele 3x"], ["Batería", "4,900 mAh · 45 W"], ["Red", "5G"]],
    conditions: [{ label: "Outlet" }, { label: "Semi nuevo" }],
    storage: [{ label: "256GB" }, { label: "512GB" }],
    colors: [
      { label: "Menta", hex: "#bfd8c8" },
      { label: "Negro azulado", hex: "#2b2d31", img: "img/p249.jpg" },
      { label: "Plata sombra", hex: "#b8bcc2", img: "img/p251.jpg" },
      { label: "Azul hielo", hex: "#c9d9e8", img: "img/p250.jpg" },
    ],
  }),
  galaxy({
    id: "galaxy-s25",
    name: "Samsung Galaxy S25 5G",
    price: 11392,
    old: 14240,
    img: "img/p251.jpg",
    featured: true,
    desc: "Compacto y potente: Snapdragon 8 Elite for Galaxy, pantalla de 6.2\" a 120 Hz y Galaxy AI para editar, traducir y buscar.",
    hl: ["Pantalla Dynamic AMOLED 2X de 6.2\"", "Snapdragon 8 Elite for Galaxy", "Cámara de 50 MP + teleobjetivo 3x", "Batería de 4,000 mAh", "Galaxy AI"],
    specs: [["Pantalla", "6.2\" Dynamic AMOLED 2X, 120 Hz"], ["Procesador", "Snapdragon 8 Elite for Galaxy"], ["Cámaras", "50 MP · 12 MP ultra gran angular · 10 MP tele 3x"], ["Batería", "4,000 mAh"], ["Red", "5G"]],
    conditions: [{ label: "Outlet" }, { label: "Semi nuevo" }],
    storage: [{ label: "128GB" }, { label: "256GB" }, { label: "512GB" }],
    colors: [
      { label: "Plata sombra", hex: "#b8bcc2", img: "img/p251.jpg" },
      { label: "Azul marino", hex: "#1f2a44", img: "img/p248.jpg" },
      { label: "Menta", hex: "#bfd8c8" },
      { label: "Azul hielo", hex: "#c9d9e8", img: "img/p250.jpg" },
      { label: "Negro azulado", hex: "#2b2d31", img: "img/p249.jpg" },
    ],
  }),
  galaxy({
    id: "galaxy-s24-ultra",
    name: "Samsung Galaxy S24 Ultra 5G",
    price: 12768,
    old: 18240,
    img: "img/p192.jpg",
    featured: true,
    desc: "Marco de titanio, S Pen integrado y cámara de 200 MP con zoom óptico 5x. Snapdragon 8 Gen 3 for Galaxy y Galaxy AI.",
    hl: ["Pantalla de 6.8\" QHD+ antirreflejante", "Snapdragon 8 Gen 3 for Galaxy", "Cámara de 200 MP + zoom 5x", "S Pen integrado", "Marco de titanio"],
    specs: [["Pantalla", "6.8\" Dynamic AMOLED 2X, 120 Hz"], ["Procesador", "Snapdragon 8 Gen 3 for Galaxy"], ["Cámaras", "200 MP · 50 MP tele 5x · 10 MP tele 3x · 12 MP UGA"], ["Batería", "5,000 mAh"], ["Extras", "S Pen · Titanio"]],
    conditions: [{ label: "Outlet" }, { label: "Semi nuevo" }],
    storage: [{ label: "256GB" }, { label: "512GB" }, { label: "1TB" }],
    colors: [
      { label: "Negro titanio", hex: "#2b2b2d", img: "img/p192.jpg" },
      { label: "Violeta titanio", hex: "#4a3d5e", img: "img/p194.jpg" },
      { label: "Gris titanio", hex: "#9a968e", img: "img/p193.jpg" },
      { label: "Blanco", hex: "#f4f4f2" },
      { label: "Amarillo titanio", hex: "#e8d9a6", img: "img/p195.jpg" },
      { label: "Verde titanio", hex: "#5b6b5a" },
      { label: "Naranja titanio", hex: "#e8b49a" },
      { label: "Azul titanio", hex: "#4c5b70" },
    ],
  }),
  galaxy({
    id: "galaxy-s24-plus",
    name: "Samsung Galaxy S24 Plus 5G",
    price: 9072,
    old: 11340,
    img: "img/p222.jpg",
    desc: "Pantalla QHD+ de 6.7\", Galaxy AI y una batería de 4,900 mAh para todo el día.",
    hl: ["Pantalla Dynamic AMOLED 2X de 6.7\" QHD+", "Cámara de 50 MP + teleobjetivo 3x", "Batería de 4,900 mAh", "Galaxy AI", "Carga rápida de 45 W"],
    specs: [["Pantalla", "6.7\" Dynamic AMOLED 2X, 120 Hz"], ["Cámaras", "50 MP · 12 MP UGA · 10 MP tele 3x"], ["Batería", "4,900 mAh · 45 W"], ["Red", "5G"]],
    conditions: [{ label: "Outlet" }, { label: "Semi nuevo" }],
    storage: [{ label: "256GB" }, { label: "512GB" }],
    colors: [
      { label: "Violeta cobalto", hex: "#4b4775", img: "img/p222.jpg" },
      { label: "Blanco", hex: "#f5f5f5" },
      { label: "Negro ónix", hex: "#2d2d30", img: "img/p224.jpg" },
      { label: "Amarillo ámbar", hex: "#f1e6be", img: "img/p223.jpg" },
      { label: "Gris mármol", hex: "#d3d3d1", img: "img/p225.jpg" },
      { label: "Verde jade", hex: "#bfd9c8" },
      { label: "Lavanda", hex: "#e4e1f2" },
      { label: "Naranja arenisca", hex: "#e2b48e" },
    ],
  }),
  galaxy({
    id: "galaxy-s24",
    name: "Samsung Galaxy S24 5G",
    price: 9349,
    old: 9540,
    img: "img/p224.jpg",
    desc: "Galaxy AI en formato compacto: pantalla de 6.2\" a 120 Hz, triple cámara con teleobjetivo 3x y marco de aluminio.",
    hl: ["Pantalla Dynamic AMOLED 2X de 6.2\"", "Cámara de 50 MP + teleobjetivo 3x", "Batería de 4,000 mAh", "Galaxy AI", "Resistencia IP68"],
    specs: [["Pantalla", "6.2\" Dynamic AMOLED 2X, 120 Hz"], ["Cámaras", "50 MP · 12 MP UGA · 10 MP tele 3x"], ["Batería", "4,000 mAh"], ["Resistencia", "IP68"], ["Red", "5G"]],
    conditions: [{ label: "Outlet" }, { label: "Semi nuevo" }],
    storage: [{ label: "128GB" }, { label: "256GB" }, { label: "512GB" }],
    colors: [
      { label: "Negro ónix", hex: "#2d2d30", img: "img/p224.jpg" },
      { label: "Amarillo ámbar", hex: "#f1e6be", img: "img/p223.jpg" },
      { label: "Blanco", hex: "#f5f5f5" },
      { label: "Violeta cobalto", hex: "#4b4775", img: "img/p222.jpg" },
      { label: "Gris mármol", hex: "#d3d3d1", img: "img/p225.jpg" },
      { label: "Verde jade", hex: "#bfd9c8" },
      { label: "Azul zafiro", hex: "#3b5a8c" },
      { label: "Naranja arenisca", hex: "#e2b48e" },
    ],
  }),
  galaxy({
    id: "galaxy-s24-fe",
    name: "Samsung Galaxy S24 FE 5G",
    price: 7192,
    old: 8990,
    img: "img/p233.jpg",
    desc: "La experiencia Galaxy S con Galaxy AI, pantalla de 6.7\" a 120 Hz y triple cámara con teleobjetivo 3x.",
    hl: ["Pantalla Dynamic AMOLED 2X de 6.7\"", "Cámara de 50 MP + teleobjetivo 3x", "Batería de 4,700 mAh", "Galaxy AI", "IP68"],
    specs: [["Pantalla", "6.7\" Dynamic AMOLED 2X, 120 Hz"], ["Cámaras", "50 MP · 12 MP UGA · 8 MP tele 3x"], ["Batería", "4,700 mAh"], ["Resistencia", "IP68"], ["Red", "5G"]],
    conditions: [{ label: "Outlet" }, { label: "Semi nuevo" }],
    storage: [{ label: "128GB" }, { label: "256GB" }],
    colors: [
      { label: "Azul", hex: "#c5d8f0", img: "img/p233.jpg" },
      { label: "Blanco", hex: "#f5f5f5" },
      { label: "Grafito", hex: "#3b3b3d", img: "img/p232.jpg" },
      { label: "Gris", hex: "#d5d5d5", img: "img/p234.jpg" },
      { label: "Menta", hex: "#cdebdd", img: "img/p235.jpg" },
      { label: "Amarillo", hex: "#f1e6a8", img: "img/p236.jpg" },
    ],
  }),
  galaxy({
    id: "galaxy-s23-ultra",
    name: "Samsung Galaxy S23 Ultra 5G",
    price: 9348,
    old: 9840,
    img: "img/p168.jpg",
    desc: "Cámara de 200 MP, S Pen integrado y Snapdragon 8 Gen 2 for Galaxy en una pantalla de 6.8\" QHD+.",
    hl: ["Pantalla Dynamic AMOLED 2X de 6.8\" QHD+", "Snapdragon 8 Gen 2 for Galaxy", "Cámara de 200 MP + zoom 10x", "S Pen integrado", "Batería de 5,000 mAh"],
    specs: [["Pantalla", "6.8\" Dynamic AMOLED 2X, 120 Hz"], ["Procesador", "Snapdragon 8 Gen 2 for Galaxy"], ["Cámaras", "200 MP · 10 MP tele 10x · 10 MP tele 3x · 12 MP UGA"], ["Batería", "5,000 mAh"], ["Extras", "S Pen"]],
    conditions: [{ label: "Outlet" }, { label: "Semi nuevo" }],
    storage: [{ label: "256GB" }, { label: "512GB" }, { label: "1TB" }],
    colors: [
      { label: "Negro", hex: "#1c1c1e", img: "img/p168.jpg" },
      { label: "Crema", hex: "#efeadb", img: "img/p169.jpg" },
      { label: "Lavanda", hex: "#e3d5e8" },
      { label: "Verde", hex: "#4e5f4e", img: "img/p167.jpg" },
      { label: "Rosa", hex: "#f3d9de" },
      { label: "Grafito", hex: "#5a5a5c" },
    ],
  }),
  galaxy({
    id: "galaxy-s23-plus",
    name: "Samsung Galaxy S23 Plus 5G",
    price: 8640,
    old: 12490,
    img: "img/p183.jpg",
    desc: "Snapdragon 8 Gen 2 for Galaxy, pantalla de 6.6\" a 120 Hz y batería de 4,700 mAh con carga de 45 W.",
    hl: ["Pantalla Dynamic AMOLED 2X de 6.6\"", "Snapdragon 8 Gen 2 for Galaxy", "Cámara de 50 MP + teleobjetivo 3x", "Batería de 4,700 mAh", "Carga de 45 W"],
    specs: [["Pantalla", "6.6\" Dynamic AMOLED 2X, 120 Hz"], ["Procesador", "Snapdragon 8 Gen 2 for Galaxy"], ["Cámaras", "50 MP · 12 MP UGA · 10 MP tele 3x"], ["Batería", "4,700 mAh · 45 W"], ["Red", "5G"]],
    conditions: [{ label: "Outlet" }, { label: "Semi nuevo" }],
    storage: [{ label: "256GB" }, { label: "512GB" }],
    colors: [
      { label: "Negro", hex: "#1c1c1e", img: "img/p183.jpg" },
      { label: "Crema", hex: "#efeadb", img: "img/p182.jpg" },
      { label: "Rosa", hex: "#e2ccc4" },
      { label: "Verde", hex: "#4e5f4e", img: "img/p184.jpg" },
      { label: "Lavanda", hex: "#e3d5e8", img: "img/p185.jpg" },
    ],
  }),
  galaxy({
    id: "galaxy-s23",
    name: "Samsung Galaxy S23 5G",
    price: 6240,
    old: 8990,
    img: "img/p209.jpg",
    desc: "Compacto de 6.1\" con Snapdragon 8 Gen 2 for Galaxy, triple cámara de 50 MP y resistencia IP68.",
    hl: ["Pantalla Dynamic AMOLED 2X de 6.1\"", "Snapdragon 8 Gen 2 for Galaxy", "Cámara de 50 MP + teleobjetivo 3x", "Batería de 3,900 mAh", "IP68"],
    specs: [["Pantalla", "6.1\" Dynamic AMOLED 2X, 120 Hz"], ["Procesador", "Snapdragon 8 Gen 2 for Galaxy"], ["Cámaras", "50 MP · 12 MP UGA · 10 MP tele 3x"], ["Batería", "3,900 mAh"], ["Red", "5G"]],
    conditions: [{ label: "Outlet" }, { label: "Semi nuevo" }],
    storage: [{ label: "128GB" }, { label: "256GB" }, { label: "512GB" }],
    colors: [
      { label: "Verde", hex: "#5e6b5a", img: "img/p209.jpg" },
      { label: "Blanco", hex: "#f5f5f2" },
      { label: "Negro", hex: "#2c2c2e", img: "img/p183.jpg" },
      { label: "Crema", hex: "#ede5d5", img: "img/p182.jpg" },
      { label: "Lavanda", hex: "#e6d4e3", img: "img/p185.jpg" },
      { label: "Grafito", hex: "#5a5a5c" },
    ],
  }),
  galaxy({
    id: "galaxy-s23-fe",
    name: "Samsung Galaxy S23 FE 5G",
    price: 4840,
    old: 7740,
    img: "img/p212.jpg",
    desc: "Lo mejor de la serie S a un gran precio: pantalla de 6.4\" a 120 Hz, triple cámara de 50 MP y resistencia IP68.",
    hl: ["Pantalla Dynamic AMOLED 2X de 6.4\"", "Cámara de 50 MP + teleobjetivo 3x", "Batería de 4,500 mAh", "IP68", "Carga inalámbrica"],
    specs: [["Pantalla", "6.4\" Dynamic AMOLED 2X, 120 Hz"], ["Cámaras", "50 MP · 12 MP UGA · 8 MP tele 3x"], ["Batería", "4,500 mAh"], ["Resistencia", "IP68"], ["Red", "5G"]],
    conditions: [{ label: "Outlet" }, { label: "Semi nuevo" }],
    storage: [{ label: "128GB" }, { label: "256GB" }],
    colors: [
      { label: "Menta", hex: "#cfe6da", img: "img/p212.jpg" },
      { label: "Crema", hex: "#f3efe6", img: "img/p215.jpg" },
      { label: "Morado", hex: "#6e557f", img: "img/p214.jpg" },
      { label: "Grafito", hex: "#3a3a3c", img: "img/p213.jpg" },
      { label: "Gris", hex: "#c9c9c9" },
    ],
  }),
  galaxy({
    id: "galaxy-z-fold4",
    name: "Samsung Galaxy Z Fold 4",
    price: 13190,
    img: "img/p270.jpg",
    badge: "Plegable",
    featured: true,
    desc: "Teléfono y tableta en uno: pantalla interior de 7.6\" y exterior de 6.2\", multitarea con barra de tareas y Snapdragon 8+ Gen 1.",
    hl: ["Pantalla interior de 7.6\" plegable", "Pantalla exterior de 6.2\"", "Snapdragon 8+ Gen 1", "Cámara de 50 MP + teleobjetivo 3x", "Multitarea tipo PC"],
    specs: [["Pantalla principal", "7.6\" Dynamic AMOLED 2X, 120 Hz"], ["Pantalla exterior", "6.2\" Dynamic AMOLED 2X"], ["Procesador", "Snapdragon 8+ Gen 1"], ["Cámaras", "50 MP · 12 MP UGA · 10 MP tele 3x"], ["Batería", "4,400 mAh"]],
    conditions: [{ label: "Outlet" }, { label: "Semi nuevo" }],
    storage: [{ label: "256GB" }, { label: "512GB" }],
    colors: [
      { label: "Verde grisáceo", hex: "#4a5a5c", img: "img/p270.jpg" },
      { label: "Beige", hex: "#e8e0cf", img: "img/p269.jpg" },
      { label: "Negro fantasma", hex: "#1c1c1e", img: "img/p268.jpg" },
      { label: "Borgoña", hex: "#6b2e3a", img: "img/p271.jpg" },
    ],
  }),
  galaxy({
    id: "galaxy-s22-ultra",
    name: "Samsung Galaxy S22 Ultra 5G",
    price: 8740,
    old: 10250,
    img: "img/p172.jpg",
    desc: "El primer Galaxy S con S Pen integrado: cámara de 108 MP con zoom 10x y pantalla de 6.8\" QHD+.",
    hl: ["Pantalla Dynamic AMOLED 2X de 6.8\" QHD+", "Cámara de 108 MP + zoom 10x", "S Pen integrado", "Batería de 5,000 mAh", "Carga de 45 W"],
    specs: [["Pantalla", "6.8\" Dynamic AMOLED 2X, 120 Hz"], ["Cámaras", "108 MP · 10 MP tele 10x · 10 MP tele 3x · 12 MP UGA"], ["Batería", "5,000 mAh · 45 W"], ["Extras", "S Pen"], ["Red", "5G"]],
    conditions: [{ label: "Outlet" }, { label: "Semi nuevo" }],
    storage: [{ label: "128GB" }, { label: "256GB" }, { label: "512GB" }],
    colors: [
      { label: "Negro fantasma", hex: "#1f1f1f", img: "img/p172.jpg" },
      { label: "Blanco fantasma", hex: "#f4f4f2", img: "img/p175.jpg" },
      { label: "Verde", hex: "#355a4c", img: "img/p174.jpg" },
      { label: "Burdeos", hex: "#6b3a44", img: "img/p173.jpg" },
      { label: "Azul cielo", hex: "#a9c4de" },
      { label: "Grafito", hex: "#4a4a4d" },
    ],
  }),
  galaxy({
    id: "galaxy-s22-plus",
    name: "Samsung Galaxy S22 Plus 5G",
    price: 5232,
    old: 6540,
    img: "img/p177.jpg",
    desc: "Pantalla de 6.6\" con brillo de hasta 1,750 nits, triple cámara de 50 MP y carga súper rápida de 45 W.",
    hl: ["Pantalla Dynamic AMOLED 2X de 6.6\"", "Cámara de 50 MP + teleobjetivo 3x", "Batería de 4,500 mAh", "Carga de 45 W", "IP68"],
    specs: [["Pantalla", "6.6\" Dynamic AMOLED 2X, 120 Hz"], ["Cámaras", "50 MP · 12 MP UGA · 10 MP tele 3x"], ["Batería", "4,500 mAh · 45 W"], ["Resistencia", "IP68"], ["Red", "5G"]],
    conditions: [{ label: "Outlet" }, { label: "Semi nuevo" }],
    storage: [{ label: "128GB" }, { label: "256GB" }],
    colors: [
      { label: "Rosa dorado", hex: "#f2d3c9", img: "img/p177.jpg" },
      { label: "Blanco fantasma", hex: "#f4f4f2", img: "img/p180.jpg" },
      { label: "Negro fantasma", hex: "#1e1e1e", img: "img/p178.jpg" },
      { label: "Verde", hex: "#1f5a4a", img: "img/p179.jpg" },
      { label: "Grafito", hex: "#4a4a4d" },
    ],
  }),
  galaxy({
    id: "galaxy-s22",
    name: "Samsung Galaxy S22 5G",
    price: 4986,
    old: 5540,
    img: "img/p180.jpg",
    desc: "Compacto de 6.1\" con triple cámara de 50 MP, pantalla a 120 Hz y resistencia IP68.",
    hl: ["Pantalla Dynamic AMOLED 2X de 6.1\"", "Cámara de 50 MP + teleobjetivo 3x", "Batería de 3,700 mAh", "IP68", "Carga inalámbrica"],
    specs: [["Pantalla", "6.1\" Dynamic AMOLED 2X, 120 Hz"], ["Cámaras", "50 MP · 12 MP UGA · 10 MP tele 3x"], ["Batería", "3,700 mAh"], ["Resistencia", "IP68"], ["Red", "5G"]],
    conditions: [{ label: "Outlet" }, { label: "Semi nuevo" }],
    storage: [{ label: "128GB" }, { label: "256GB" }],
    colors: [
      { label: "Blanco fantasma", hex: "#f4f4f2", img: "img/p180.jpg" },
      { label: "Negro fantasma", hex: "#1e1e1e", img: "img/p178.jpg" },
      { label: "Verde", hex: "#1f5a4a", img: "img/p179.jpg" },
      { label: "Rosa dorado", hex: "#f2d3c9", img: "img/p177.jpg" },
      { label: "Azul cielo", hex: "#a9c4de" },
      { label: "Grafito", hex: "#4a4a4d" },
      { label: "Violeta", hex: "#c3a8e0" },
      { label: "Crema", hex: "#efeadb" },
    ],
  }),
  galaxy({
    id: "galaxy-a56",
    name: "Samsung Galaxy A56 5G",
    price: 6490,
    img: "img/p261.jpg",
    badge: "Nuevo",
    featured: true,
    desc: "El Galaxy A más avanzado: pantalla Super AMOLED de 6.7\" a 120 Hz, Exynos 1580, Awesome Intelligence y carga de 45 W.",
    hl: ["Pantalla Super AMOLED de 6.7\" 120 Hz", "Exynos 1580", "Cámara de 50 MP", "Batería de 5,000 mAh · 45 W", "IP67"],
    specs: [["Pantalla", "6.7\" Super AMOLED, 120 Hz"], ["Procesador", "Exynos 1580"], ["Cámaras", "50 MP · 12 MP UGA · 5 MP macro"], ["Batería", "5,000 mAh · 45 W"], ["Red", "5G"]],
    conditions: [{ label: "Outlet" }, { label: "Semi nuevo" }],
    storage: [{ label: "128GB" }, { label: "256GB" }],
    colors: [
      { label: "Rosa", hex: "#f0d8e2", img: "img/p261.jpg" },
      { label: "Gris claro", hex: "#d9dbdc", img: "img/p259.jpg" },
      { label: "Olivo", hex: "#afc0b0", img: "img/p260.jpg" },
      { label: "Grafito", hex: "#5a5b5d", img: "img/p258.jpg" },
    ],
  }),
  galaxy({
    id: "galaxy-a55",
    name: "Samsung Galaxy A55 5G",
    price: 4990,
    old: 5940,
    img: "img/p240.jpg",
    desc: "Marco de metal y vidrio Gorilla Glass Victus+, pantalla Super AMOLED de 6.6\" y cámara de 50 MP con OIS.",
    hl: ["Pantalla Super AMOLED de 6.6\" 120 Hz", "Marco de metal", "Cámara de 50 MP con OIS", "Batería de 5,000 mAh", "IP67"],
    specs: [["Pantalla", "6.6\" Super AMOLED, 120 Hz"], ["Procesador", "Exynos 1480"], ["Cámaras", "50 MP · 12 MP UGA · 5 MP macro"], ["Batería", "5,000 mAh"], ["Red", "5G"]],
    conditions: [{ label: "Outlet" }, { label: "Semi nuevo" }],
    storage: [{ label: "128GB" }, { label: "256GB" }],
    colors: [
      { label: "Lila", hex: "#e7d9f0", img: "img/p240.jpg" },
      { label: "Azul marino", hex: "#262b3d", img: "img/p238.jpg" },
      { label: "Azul hielo", hex: "#d5e2f2", img: "img/p239.jpg" },
      { label: "Limón", hex: "#f3f0a8", img: "img/p241.jpg" },
    ],
  }),
  galaxy({
    id: "galaxy-a35",
    name: "Samsung Galaxy A35 5G",
    price: 3240,
    old: 3840,
    img: "img/p254.jpg",
    featured: true,
    desc: "Pantalla Super AMOLED de 6.6\" a 120 Hz, cámara de 50 MP con OIS, batería de 5,000 mAh y resistencia IP67.",
    hl: ["Pantalla Super AMOLED de 6.6\" 120 Hz", "Cámara de 50 MP con OIS", "Batería de 5,000 mAh", "IP67", "5G"],
    specs: [["Pantalla", "6.6\" Super AMOLED, 120 Hz"], ["Procesador", "Exynos 1380"], ["Cámaras", "50 MP · 8 MP UGA · 5 MP macro"], ["Batería", "5,000 mAh"], ["Red", "5G"]],
    conditions: [{ label: "Outlet" }, { label: "Semi nuevo" }],
    storage: [{ label: "128GB" }, { label: "256GB" }],
    colors: [
      { label: "Azul marino", hex: "#262b3d", img: "img/p254.jpg" },
      { label: "Azul hielo", hex: "#dce4f2", img: "img/p256.jpg" },
      { label: "Lila", hex: "#e6d6ee", img: "img/p255.jpg" },
      { label: "Limón", hex: "#f3f0b0", img: "img/p253.jpg" },
    ],
  }),
  galaxy({
    id: "galaxy-a34",
    name: "Samsung Galaxy A34 5G",
    price: 2290,
    img: "img/p246.jpg",
    desc: "Pantalla Super AMOLED de 6.6\" a 120 Hz, triple cámara de 48 MP con OIS y batería de 5,000 mAh.",
    hl: ["Pantalla Super AMOLED de 6.6\" 120 Hz", "Cámara de 48 MP con OIS", "Batería de 5,000 mAh", "IP67", "5G"],
    specs: [["Pantalla", "6.6\" Super AMOLED, 120 Hz"], ["Procesador", "Dimensity 1080"], ["Cámaras", "48 MP · 8 MP UGA · 5 MP macro"], ["Batería", "5,000 mAh"], ["Red", "5G"]],
    conditions: [{ label: "Outlet" }, { label: "Semi nuevo" }],
    storage: [{ label: "128GB" }, { label: "256GB" }],
    colors: [
      { label: "Grafito", hex: "#2f2f31", img: "img/p246.jpg" },
      { label: "Plata", hex: "#e3ecec", img: "img/p244.jpg" },
      { label: "Lima", hex: "#ddeb9a", img: "img/p245.jpg" },
      { label: "Violeta", hex: "#a5a0e8", img: "img/p243.jpg" },
    ],
  }),
  galaxy({
    id: "galaxy-a53",
    name: "Samsung Galaxy A53 5G",
    price: 2640,
    img: "img/p218.jpg",
    desc: "Pantalla Super AMOLED de 6.5\" a 120 Hz, cuádruple cámara de 64 MP con OIS y batería de 5,000 mAh.",
    hl: ["Pantalla Super AMOLED de 6.5\" 120 Hz", "Cámara de 64 MP con OIS", "Batería de 5,000 mAh", "IP67", "5G"],
    specs: [["Pantalla", "6.5\" Super AMOLED, 120 Hz"], ["Procesador", "Exynos 1280"], ["Cámaras", "64 MP · 12 MP UGA · 5 MP macro · 5 MP profundidad"], ["Batería", "5,000 mAh"], ["Red", "5G"]],
    conditions: [{ label: "Outlet" }, { label: "Semi nuevo" }],
    storage: [{ label: "128GB" }, { label: "256GB" }],
    colors: [
      { label: "Azul", hex: "#b9d2ec", img: "img/p218.jpg" },
      { label: "Blanco", hex: "#f4f4f4", img: "img/p220.jpg" },
      { label: "Negro", hex: "#2b2b2b", img: "img/p219.jpg" },
      { label: "Durazno", hex: "#f7c9a6", img: "img/p217.jpg" },
    ],
  }),
  galaxy({
    id: "galaxy-a52",
    name: "Samsung Galaxy A52",
    price: 2340,
    img: "img/p203.jpg",
    desc: "Pantalla Super AMOLED de 6.5\" a 90 Hz, cuádruple cámara de 64 MP con OIS y resistencia IP67.",
    hl: ["Pantalla Super AMOLED de 6.5\" 90 Hz", "Cámara de 64 MP con OIS", "Batería de 4,500 mAh", "IP67", "Bocinas estéreo"],
    specs: [["Pantalla", "6.5\" Super AMOLED, 90 Hz"], ["Cámaras", "64 MP · 12 MP UGA · 5 MP macro · 5 MP profundidad"], ["Batería", "4,500 mAh"], ["Resistencia", "IP67"]],
    conditions: [{ label: "Outlet" }, { label: "Semi nuevo" }],
    storage: [{ label: "128GB" }],
    colors: [
      { label: "Menta", hex: "#c8ebdd", img: "img/p203.jpg" },
      { label: "Violeta", hex: "#cfc3ea", img: "img/p204.jpg" },
      { label: "Blanco", hex: "#f5f5f5", img: "img/p205.jpg" },
      { label: "Negro", hex: "#232323", img: "img/p202.jpg" },
    ],
  }),
  galaxy({
    id: "galaxy-a32",
    name: "Samsung Galaxy A32",
    price: 2040,
    img: "img/p188.jpg",
    desc: "Pantalla Super AMOLED de 6.4\" a 90 Hz, cuádruple cámara de 64 MP y batería de 5,000 mAh.",
    hl: ["Pantalla Super AMOLED de 6.4\" 90 Hz", "Cámara de 64 MP", "Batería de 5,000 mAh", "Lector de huella en pantalla"],
    specs: [["Pantalla", "6.4\" Super AMOLED, 90 Hz"], ["Cámaras", "64 MP · 8 MP UGA · 5 MP macro · 5 MP profundidad"], ["Batería", "5,000 mAh"], ["Seguridad", "Huella en pantalla"]],
    conditions: [{ label: "Outlet" }, { label: "Semi nuevo" }],
    storage: [{ label: "32GB" }, { label: "64GB" }, { label: "128GB" }],
    colors: [
      { label: "Azul", hex: "#8ec1e6", img: "img/p188.jpg" },
      { label: "Blanco", hex: "#f5f5f5", img: "img/p190.jpg" },
      { label: "Negro", hex: "#1e1e1e", img: "img/p187.jpg" },
      { label: "Violeta", hex: "#c9c0e8", img: "img/p189.jpg" },
    ],
  }),
  galaxy({
    id: "galaxy-a15",
    name: "Samsung Galaxy A15",
    price: 2490,
    old: 2940,
    img: "img/p265.jpg",
    desc: "Pantalla Super AMOLED de 6.5\" a 90 Hz, triple cámara de 50 MP y batería de 5,000 mAh con carga rápida de 25 W.",
    hl: ["Pantalla Super AMOLED de 6.5\" 90 Hz", "Cámara de 50 MP", "Batería de 5,000 mAh", "Carga rápida de 25 W"],
    specs: [["Pantalla", "6.5\" Super AMOLED, 90 Hz"], ["Procesador", "Helio G99"], ["Cámaras", "50 MP · 5 MP UGA · 2 MP macro"], ["Batería", "5,000 mAh · 25 W"]],
    conditions: [{ label: "Outlet" }, { label: "Semi nuevo" }],
    storage: [{ label: "128GB" }, { label: "256GB" }],
    colors: [
      { label: "Azul negro", hex: "#1e2235", img: "img/p265.jpg" },
      { label: "Azul claro", hex: "#e4e6f2", img: "img/p264.jpg" },
      { label: "Azul", hex: "#7f9cc9", img: "img/p266.jpg" },
      { label: "Amarillo", hex: "#f1efa8", img: "img/p263.jpg" },
    ],
  }),

  /* ===================== CONSOLAS ===================== */
  {
    id: "switch2-mkw-fisico",
    cat: "consolas",
    brand: "Nintendo",
    name: "Nintendo Switch 2 + Mario Kart World (físico)",
    title: "Consola Nintendo Switch 2 con Mario Kart World físico y adaptador de corriente",
    price: 11999.99,
    img: "img/p2.jpg",
    badge: "Nuevo",
    featured: true,
    desc: "La nueva generación de Nintendo: una consola híbrida para jugar en TV, sobremesa o portátil. Incluye Mario Kart World en formato físico, con un mundo abierto interconectado, modo Supervivencia para 24 jugadores y GameChat con CameraPlay.",
    hl: ["Pantalla táctil LCD de 7.9\" Full HD (1080p)", "Hasta 4K y 120 fps en TV compatible", "256 GB, expandible con microSD Express", "Joy-Con 2 con conectores magnéticos", "Wi-Fi 6 y Bluetooth 5.3"],
    specs: [["Plataforma", "Nintendo Switch 2"], ["Almacenamiento", "256 GB"], ["Pantalla", "7.9\" LCD 1080p"], ["Juego incluido", "Mario Kart World (físico)"], ["Incluye", "Adaptador de corriente"], ["Condición", "Nuevo"], ["SKU", "7506127526940"]],
  },
  {
    id: "switch2",
    cat: "consolas",
    brand: "Nintendo",
    name: "Nintendo Switch 2",
    title: "Consola Nintendo Switch 2 con adaptador",
    price: 10999.99,
    img: "img/p4.jpg",
    badge: "Nuevo",
    desc: "Consola híbrida de nueva generación con diseño en azul y rojo. Juega en modo portátil, semiportátil o conectada a la TV, con GameChat integrado para chat de voz y video.",
    hl: ["Pantalla LCD táctil de 7.9\" Full HD", "Hasta 4K y 120 fps en TV compatible", "Joy-Con 2 con conectores magnéticos", "GameChat integrado", "256 GB, Wi-Fi 6 y Bluetooth 5.3"],
    specs: [["Plataforma", "Nintendo Switch 2"], ["Almacenamiento", "256 GB (microSD Express)"], ["Pantalla", "7.9\" LCD 1080p"], ["Incluye", "Adaptador de corriente AC"], ["Condición", "Nuevo"], ["SKU", "7506127526933"]],
  },
  {
    id: "switch2-mkw-digital",
    cat: "consolas",
    brand: "Nintendo",
    name: "Nintendo Switch 2 + Mario Kart World (digital)",
    price: 8999.99,
    img: "img/p38.jpg",
    desc: "Consola Nintendo Switch 2 con Mario Kart World en descarga digital: mundo abierto con climas dinámicos, hasta 24 jugadores en línea y batallas de globos y monedas.",
    hl: ["Mario Kart World en versión digital", "Mundo abierto con climas dinámicos", "Hasta 24 jugadores en línea", "Batallas de globos y monedas"],
    specs: [["Plataforma", "Nintendo Switch 2"], ["Juego incluido", "Mario Kart World (descarga)"], ["Condición", "Nuevo"], ["SKU", "045496885618"]],
  },
  {
    id: "ps5-fortnite",
    cat: "consolas",
    brand: "Sony",
    name: "PlayStation 5 Digital · Fortnite Flowering Chaos",
    price: 11999.99,
    img: "img/p8.jpg",
    badge: "Nuevo",
    featured: true,
    desc: "PS5 Edición Digital en diseño Slim con tiempos de carga ultrarrápidos y 825 GB de SSD. Incluye el paquete Fortnite Flowering Chaos con cosméticos de temática floral y moneda virtual.",
    hl: ["Edición Digital, diseño Slim", "825 GB SSD", "Traje Florín (incluye estilo LEGO)", "Mochila retro Blossom y Pico Pala Floral", "Moneda virtual para Fortnite"],
    specs: [["Plataforma", "PlayStation 5"], ["Almacenamiento", "825 GB SSD"], ["Formato", "Digital (sin lector)"], ["Clasificación", "B (12+)"], ["Condición", "Nuevo"], ["SKU", "711719022046"]],
  },
  {
    id: "ps5-megapack",
    cat: "consolas",
    brand: "Sony",
    name: "PlayStation 5 Digital Megapack · GT7 + Astro Bot",
    price: 9999.99,
    img: "img/p36.jpg",
    desc: "PS5 Digital Edition con Astro Bot y Gran Turismo 7 en versión digital. Compacta, sin lector de discos, con SSD de 825 GB y control inalámbrico DualSense.",
    hl: ["PS5 Digital Edition 825 GB", "Astro Bot (digital)", "Gran Turismo 7 (digital)", "Trazado de rayos y audio 3D", "Control DualSense incluido"],
    specs: [["Plataforma", "PlayStation 5"], ["Almacenamiento", "825 GB SSD"], ["Juegos", "Astro Bot · Gran Turismo 7"], ["Condición", "Nuevo"], ["SKU", "711719570936"]],
  },
  {
    id: "xsx-galaxy-2tb",
    cat: "consolas",
    brand: "Xbox",
    name: "Xbox Series X Galaxy Black 2 TB",
    price: 24999.99,
    img: "img/p16.jpg",
    badge: "Edición especial",
    featured: true,
    desc: "La Xbox más potente con SSD de 2 TB y Xbox Velocity Architecture. Compatible con Dolby Vision y Dolby Atmos, con resolución nativa hasta 4K y hasta 120 FPS.",
    hl: ["SSD de 2 TB", "4K nativo y hasta 120 FPS", "Compatible con 8K HDR", "Dolby Vision y Dolby Atmos", "Control inalámbrico incluido"],
    specs: [["Plataforma", "Xbox Series X"], ["Almacenamiento", "2 TB SSD"], ["Resolución", "Hasta 4K / 8K HDR"], ["Condición", "Nuevo"], ["SKU", "196388364350"]],
  },
  {
    id: "xsx",
    cat: "consolas",
    brand: "Xbox",
    name: "Xbox Series X",
    price: 17799.99,
    img: "img/p26.jpg",
    badge: "Nuevo",
    desc: "La Xbox más rápida y potente: hasta 120 FPS, HDR y 4K auténtico. SSD personalizado, Reanudación rápida y un diseño con flujo de aire silencioso.",
    hl: ["Hasta 120 FPS con HDR y 4K", "SSD personalizado", "Reanudación rápida", "AMD Zen 2 y RDNA 2 con Ray Tracing", "Ventilador silencioso"],
    specs: [["Plataforma", "Xbox Series X"], ["Arquitectura", "AMD Zen 2 + RDNA 2"], ["Formato", "Con lector de discos"], ["Condición", "Nuevo"], ["SKU", "889842640762"]],
  },
  {
    id: "xsx-digital-1tb",
    cat: "consolas",
    brand: "Xbox",
    name: "Xbox Series X Digital 1 TB · Robot White",
    price: 16799.99,
    img: "img/p22.jpg",
    badge: "Nuevo",
    desc: "Xbox Series X totalmente digital con SSD de 1 TB en Robot White. Juegos a 4K y hasta 120 FPS, Quick Resume y miles de títulos de cuatro generaciones.",
    hl: ["Digital con SSD de 1 TB", "12 teraflops de potencia gráfica", "4K y hasta 120 FPS", "Quick Resume", "Trazado de rayos DirectX"],
    specs: [["Plataforma", "Xbox Series X"], ["Almacenamiento", "1 TB SSD"], ["Formato", "Digital"], ["Color", "Robot White"], ["Condición", "Nuevo"], ["SKU", "196388363865"]],
  },
  {
    id: "xsx-recert",
    cat: "consolas",
    brand: "Xbox",
    name: "Xbox Series X (recertificada)",
    price: 16799.99,
    img: "img/p18.jpg",
    badge: "Recertificado",
    desc: "Xbox Series X inspeccionada, evaluada y preparada para garantizar su correcto funcionamiento. Gráficos hasta 4K, Ray Tracing y SSD de alta velocidad.",
    hl: ["Resolución de hasta 4K", "Xbox Velocity Architecture", "Ray Tracing compatible", "Retrocompatible con Xbox One y anteriores", "Producto recertificado"],
    specs: [["Plataforma", "Xbox Series X"], ["Formato", "Con lector de discos"], ["Condición", "Recertificado"], ["SKU", "889842641097"]],
  },
  {
    id: "xsx-digital-recert",
    cat: "consolas",
    brand: "Xbox",
    name: "Xbox Series X Digital 1 TB (recertificada)",
    price: 14799.99,
    img: "img/p10.jpg",
    badge: "Recertificado",
    desc: "Xbox Series X Digital de 1 TB, sin discos físicos. Resolución de hasta 4K y tiempos de carga reducidos. Verificada para asegurar su correcto desempeño.",
    hl: ["Hasta 4K en juegos compatibles", "Tiempos de carga reducidos", "Xbox Velocity Architecture", "100 % digital", "Producto recertificado"],
    specs: [["Plataforma", "Xbox Series X"], ["Almacenamiento", "1 TB"], ["Formato", "Digital"], ["Condición", "Recertificado"], ["SKU", "196388364121"]],
  },
  {
    id: "xss-1tb",
    cat: "consolas",
    brand: "Xbox",
    name: "Xbox Series S 1 TB",
    price: 10999.99,
    img: "img/p20.jpg",
    badge: "Nuevo",
    desc: "Xbox Series S de nueva generación con 1 TB de almacenamiento. Procesador de 8 núcleos, transiciones fluidas en alta definición y descargas más rápidas.",
    hl: ["Almacenamiento de 1 TB", "Procesador de 8 núcleos", "Imagen fluida en alta definición", "USB y salida HDMI"],
    specs: [["Plataforma", "Xbox Series S"], ["Almacenamiento", "1 TB"], ["Formato", "Digital"], ["Condición", "Nuevo"], ["SKU", "196388363155"]],
  },
  {
    id: "xss",
    cat: "consolas",
    brand: "Xbox",
    name: "Xbox Series S",
    price: 8799.99,
    img: "img/p12.jpg",
    badge: "Nuevo",
    desc: "Consola totalmente digital con rendimiento de nueva generación. Compatible con Xbox Game Pass Ultimate (se vende por separado) y miles de títulos retrocompatibles.",
    hl: ["Smart Delivery", "100 % digital", "SSD personalizada con Velocity Architecture", "Juegos de hasta 120 FPS", "Reanudación rápida"],
    specs: [["Plataforma", "Xbox Series S"], ["Formato", "Digital"], ["Condición", "Nuevo"], ["SKU", "889842651355"]],
  },
  {
    id: "switch-oled-pokemon",
    cat: "consolas",
    brand: "Nintendo",
    name: "Nintendo Switch OLED · Edición Pokémon Escarlata y Violeta",
    price: 6599.99,
    img: "img/p28.jpg",
    badge: "Edición especial",
    desc: "Switch OLED con ilustraciones de Koraidon, Miraidon, Sprigatito, Fuecoco y Quaxly. Pantalla OLED de 7\", soporte ajustable, base con puerto LAN y audio mejorado.",
    hl: ["Pantalla OLED de 7\"", "Soporte ajustable y amplio", "Puerto LAN en la base", "64 GB de almacenamiento", "Modo TV, semiportátil y portátil"],
    specs: [["Plataforma", "Nintendo Switch"], ["Pantalla", "OLED 7\""], ["Almacenamiento", "64 GB"], ["Condición", "Nuevo"], ["SKU", "045496597399"]],
  },
  {
    id: "switch-oled-wonder",
    cat: "consolas",
    brand: "Nintendo",
    name: "Nintendo Switch OLED Blanca + Mario Wonder",
    price: 5999.99,
    img: "img/p6.jpg",
    badge: "Bundle",
    featured: true,
    desc: "Switch OLED blanca con Super Mario Bros. Wonder y 3 meses de Nintendo Switch Online: juego en línea, clásicos de NES y Super NES y respaldo en la nube.",
    hl: ["Pantalla OLED de 7\"", "Super Mario Bros. Wonder incluido", "3 meses de Nintendo Switch Online", "64 GB de almacenamiento", "Hasta 9 horas de batería"],
    specs: [["Plataforma", "Nintendo Switch"], ["Pantalla", "OLED 7\""], ["Almacenamiento", "64 GB"], ["Incluye", "Base, HDMI, adaptador, Joy-Con blancos con correas"], ["Condición", "Nuevo"], ["SKU", "045496885489"]],
  },
  {
    id: "switch-wonder",
    cat: "consolas",
    brand: "Nintendo",
    name: "Nintendo Switch + Mario Wonder",
    price: 4999.99,
    img: "img/p14.jpg",
    badge: "Bundle",
    desc: "Nintendo Switch con Super Mario Bros. Wonder y membresía de Nintendo Switch Online. Juega en TV, portátil o sobremesa con Joy-Con neón.",
    hl: ["Super Mario Bros. Wonder incluido", "Membresía Nintendo Switch Online", "Joy-Con color neón", "Dock para TV", "32 GB de almacenamiento"],
    specs: [["Plataforma", "Nintendo Switch"], ["Almacenamiento", "32 GB"], ["Clasificación", "Todo público"], ["Condición", "Nuevo"], ["SKU", "045496885373"]],
  },
  {
    id: "switch-neon",
    cat: "consolas",
    brand: "Nintendo",
    name: "Nintendo Switch · Joy-Con azul y rojo neón",
    price: 3999.99,
    img: "img/p30.jpg",
    badge: "Nuevo",
    desc: "La consola de casa que también te llevas a donde vayas. Pasa de la base al modo portátil al instante y juega con los Joy-Con por separado o en el agarre.",
    hl: ["Pantalla de 6.2\"", "Joy-Con azul y rojo neón", "Del modo TV al portátil al instante", "HD Rumble y sensor de movimiento", "Multijugador para dos al instante"],
    specs: [["Plataforma", "Nintendo Switch"], ["Pantalla", "6.2\""], ["Almacenamiento", "32 GB"], ["Condición", "Nuevo"], ["SKU", "045496882174"]],
  },
  {
    id: "mochila-xss",
    cat: "consolas",
    brand: "RDS",
    name: "Mochila RDS Game Traveler para Xbox Series S",
    price: 699.99,
    img: "img/p40.jpg",
    badge: "Accesorio",
    desc: "Mochila acolchada para llevar tu Xbox Series S y sus accesorios. Bolsillo principal para la consola, bolsillo frontal para control y cables, y divisor elástico para la tarjeta de expansión. Consola y accesorios se venden por separado.",
    hl: ["Compatible con Xbox Series S", "Estuche de nailon acolchado", "Bolsillo frontal para control y cables", "Correa de hombro ajustable", "Divisor para tarjeta de expansión"],
    specs: [["Compatibilidad", "Xbox Series S"], ["Tipo", "Mochila de transporte"], ["SKU", "663293111978"]],
  },

  /* ===================== RETRO ===================== */
  {
    id: "c64-mini",
    cat: "retro",
    brand: "THEC64",
    name: "THEC64 Mini",
    price: 699.99,
    img: "img/p24.jpg",
    badge: "Clásico",
    desc: "La legendaria computadora C64 de 1982 regresa en miniatura. Conéctala a cualquier TV por HDMI y juega 64 clásicos con licencia como California Games, Speedball 2, Paradroid e Impossible Mission.",
    hl: ["64 juegos clásicos con licencia", "Conexión HDMI a cualquier TV", "Salida en 720p", "Joystick clásico incluido"],
    specs: [["Juegos incluidos", "64"], ["Video", "HDMI 720p"], ["Incluye", "Joystick"], ["SKU", "884095193539"]],
  },
  {
    id: "atari-flashback-2",
    cat: "retro",
    brand: "Atari",
    name: "Atari Flashback Blast Vol. 2",
    price: 399.99,
    img: "img/p32.jpg",
    desc: "Consola tipo dongle HDMI con control inalámbrico y 20 clásicos de Atari en HD: Adventure, Asteroids, Crystal Castles, Haunted House, Missile Command, Video Pinball y más.",
    hl: ["20 juegos clásicos integrados", "Resolución HD por HDMI", "Control inalámbrico", "Guarda y rebobina partidas"],
    specs: [["Juegos incluidos", "20"], ["Formato", "Dongle HDMI"], ["Control", "Inalámbrico"], ["SKU", "818858029544"]],
  },
  {
    id: "namco-flashback",
    cat: "retro",
    brand: "Bandai Namco",
    name: "Bandai Namco Flashback Blast",
    price: 399.99,
    img: "img/p34.jpg",
    desc: "Ocho clásicos de arcade en HD con control inalámbrico: Pac-Man, Galaga, Dig Dug, Galaxian, Mappy, Sky Kid, The Tower of Druaga y Xevious.",
    hl: ["8 juegos clásicos integrados", "Resolución HD por HDMI", "Control inalámbrico", "Pac-Man, Galaga y Dig Dug"],
    specs: [["Juegos incluidos", "8"], ["Formato", "Dongle HDMI"], ["Control", "Inalámbrico"], ["SKU", "818858029551"]],
  },

  /* ===================== MOUSE ===================== */
  {
    id: "rog-harpe-ace",
    cat: "mouse",
    brand: "ASUS ROG",
    name: "ASUS ROG Harpe Ace Aim Lab Edition",
    price: 1239,
    img: "img/p95.jpg",
    badge: "Inalámbrico",
    featured: true,
    desc: "Mouse inalámbrico desarrollado con profesionales de esports para máxima estabilidad al deslizar. Sensor óptico ROG AimPoint de 36,000 dpi con menos de 1 % de desviación.",
    hl: ["Sensor ROG AimPoint de 36,000 dpi", "Conexión USB 2.0 y Bluetooth", "Forma diseñada con profesionales de esports", "AURA Sync", "Batería de ion de litio"],
    specs: [["Modelo", "P713"], ["Sensor", "Óptico ROG AimPoint"], ["Resolución", "36,000 dpi"], ["Conexión", "Inalámbrica USB 2.0 / Bluetooth"], ["Botones", "5"], ["Batería", "Ion de litio"]],
    options: [
      {
        key: "color",
        label: "Color",
        type: "swatch",
        values: [
          { label: "Negro", hex: "#141414", img: "img/p95.jpg", price: 1239 },
          { label: "Blanco", hex: "#f2f3f5", img: "img/p89.jpg", price: 1549 },
        ],
      },
    ],
  },
  {
    id: "g502-hero",
    cat: "mouse",
    brand: "Logitech G",
    name: "Logitech G502 HERO",
    price: 1299,
    img: "img/p93.jpg",
    desc: "Sensor HERO 16K con más de 400 ips y 100–16,000 dpi sin aceleración. 11 botones programables, cinco pesas ajustables y switches para 50 millones de clics.",
    hl: ["Sensor HERO 16K", "11 botones programables", "5 pesas de 3.6 g", "Switches de 50 millones de clics", "RGB LIGHTSYNC"],
    specs: [["Resolución", "16,000 dpi"], ["Botones", "11"], ["Frecuencia de sondeo", "1000 Hz"], ["Tiempo de respuesta", "1 ms"], ["Aceleración", "40 G"], ["Memoria integrada", "Sí"], ["Factor de forma", "Diestro"]],
  },
  {
    id: "evga-x17",
    cat: "mouse",
    brand: "EVGA",
    name: "EVGA X17",
    price: 979,
    old: 1099,
    img: "img/p101.jpg",
    desc: "Microprocesador ARM Cortex-M33 de 32 bits con tasa de reporte nativa de 8000 Hz. Botones con resortes precargados para respuesta inmediata y 5 perfiles por hardware.",
    hl: ["16,000 dpi", "Reporte nativo de 8000 Hz", "10 botones", "5 perfiles por hardware", "Botón de sniper para FPS"],
    specs: [["Resolución", "16,000 dpi"], ["Frecuencia", "8000 Hz"], ["Botones", "10"], ["Cable", "2 m"], ["Color", "Gris"], ["Compatibilidad", "Windows 10 / 8.1 / 7"]],
  },
  {
    id: "g203",
    cat: "mouse",
    brand: "Logitech G",
    name: "Logitech G203 LIGHTSYNC",
    price: 409,
    old: 499,
    img: "img/p91.jpg",
    featured: true,
    desc: "Clásico diseño de seis botones con sensor de 200–8,000 dpi y onda de color RGB LIGHTSYNC de 16.8 millones de colores. Programa hasta 5 preajustes con Logitech G HUB.",
    hl: ["Sensor de hasta 8,000 dpi", "6 botones programables", "RGB LIGHTSYNC", "1000 Hz · 1 ms", "Cable de 2.1 m"],
    specs: [["Resolución", "8,000 dpi"], ["Botones", "6 programables"], ["Frecuencia de sondeo", "1000 Hz"], ["Tiempo de respuesta", "1 ms"], ["Cable", "2.1 m"], ["Interfaz", "USB tipo A"]],
    options: [
      {
        key: "color",
        label: "Color",
        type: "swatch",
        values: [
          { label: "Negro", hex: "#161616", img: "img/p91.jpg", price: 409, old: 499 },
          { label: "Azul", hex: "#2f6fd6", img: "img/p107.jpg", price: 449, old: null },
        ],
      },
    ],
  },
  {
    id: "neros-rgb",
    cat: "mouse",
    brand: "Thermaltake",
    name: "Tt eSPORTS NEROS RGB",
    price: 383.89,
    old: 449,
    img: "img/p99.jpg",
    desc: "Motor óptico Pixart PMW-3050 con 1000 reportes por segundo y switches para 20 millones de clics. DPI ajustable al vuelo y diseño ergonómico con agarre lateral.",
    hl: ["Sensor Pixart PMW-3050", "Hasta 3,200 dpi", "6 botones programables", "20 millones de clics", "DPI: 750 / 1500 / 2000 / 2500 / 3200"],
    specs: [["Modelo", "EMO-NRR-WDOTBK-01"], ["Resolución", "3,200 dpi"], ["Botones", "6 programables"], ["Cable", "1.8 m"], ["Interfaz", "USB"]],
  },
  {
    id: "claymore-2001",
    cat: "mouse",
    brand: "Yeyian",
    name: "Yeyian Claymore 2001",
    price: 366.8,
    old: 429,
    img: "img/p109.jpg",
    desc: "Mouse gamer óptico con sensor de hasta 12,000 dpi, 6 botones e iluminación LED RGB en un perfil ligero.",
    hl: ["Hasta 12,000 dpi", "6 botones", "Iluminación LED RGB", "Sensor óptico"],
    specs: [["Resolución", "12,000 dpi"], ["Botones", "6"], ["Interfaz", "USB"], ["Compatibilidad", "Windows 10 / 8.1 / 7"]],
  },
  {
    id: "forge-gm320",
    cat: "mouse",
    brand: "MSI",
    name: "MSI FORGE GM320",
    price: 209,
    img: "img/p113.jpg",
    desc: "Mouse ambidiestro con sensor de 12,800 dpi, 7 botones y switches para 20 millones de clics. Cable trenzado e iluminación RGB.",
    hl: ["Hasta 12,800 dpi", "7 botones", "20 millones de clics", "Cable trenzado de 1.5 m", "Iluminación RGB"],
    specs: [["Resolución", "12,800 dpi"], ["Botones", "7"], ["Factor de forma", "Ambidiestro"], ["Cable", "1.5 m trenzado"], ["Interfaz", "USB tipo A"]],
  },
  {
    id: "manhattan-190220",
    cat: "mouse",
    brand: "Manhattan",
    name: "Manhattan MAN-190220",
    price: 169,
    img: "img/p97.jpg",
    desc: "Mouse gamer diestro con iluminación LED, 7 botones y 4 modos de resolución de hasta 7,200 dpi.",
    hl: ["Hasta 7,200 dpi", "7 botones", "4 modos de DPI", "Iluminación LED"],
    specs: [["Resolución", "7,200 dpi"], ["Botones", "7"], ["Factor de forma", "Diestro"], ["Cable", "1.4 m"], ["Interfaz", "USB tipo A"]],
  },
  {
    id: "zeus-e3",
    cat: "mouse",
    brand: "Gamdias",
    name: "Gamdias Zeus E3",
    price: 161.6,
    old: 189,
    img: "img/p103.jpg",
    desc: "Iluminación de varios colores que rodea la palma y las yemas de los dedos, con un diseño ergonómico que da mejor soporte al antebrazo.",
    hl: ["Hasta 3,600 dpi", "7 botones", "Iluminación RGB envolvente", "Diseño ergonómico"],
    specs: [["Resolución", "3,600 dpi"], ["Botones", "7"], ["Frecuencia", "125 Hz"], ["Cable", "1.5 m"], ["Interfaz", "USB"]],
  },
  {
    id: "naceb-osiris",
    cat: "mouse",
    brand: "NACEB",
    name: "NACEB OSIRIS NA-0964",
    price: 129,
    img: "img/p105.jpg",
    desc: "Mouse alámbrico ambidiestro con 7 botones, 6 modos de resolución de hasta 7,200 dpi e iluminación multicolor.",
    hl: ["Hasta 7,200 dpi", "7 botones", "6 modos de DPI", "Ambidiestro", "Windows y Mac"],
    specs: [["Resolución", "7,200 dpi"], ["Botones", "7"], ["Frecuencia", "125 Hz"], ["Cable", "1.5 m"], ["Interfaz", "USB tipo A"]],
  },
  {
    id: "raptor-mg2",
    cat: "mouse",
    brand: "Balam Rush",
    name: "Balam Rush Raptor Plus MG2",
    price: 119,
    img: "img/p115.jpg",
    desc: "Mouse alámbrico con sensor óptico, 6 botones y frecuencia de 1000 Hz con iluminación RGB.",
    hl: ["Hasta 7,600 dpi", "6 botones", "1000 Hz", "Iluminación RGB"],
    specs: [["Resolución", "7,600 dpi"], ["Botones", "6"], ["Frecuencia", "1000 Hz"], ["Cable", "1.5 m"], ["Interfaz", "USB tipo A"]],
  },
  {
    id: "xzeal-xst401",
    cat: "mouse",
    brand: "Xzeal",
    name: "Xzeal Starter XST-401",
    price: 109,
    img: "img/p111.jpg",
    desc: "Mouse diestro de 6 botones con sensor de hasta 7,200 dpi, aceleración de 20 G y aro de iluminación RGB.",
    hl: ["Hasta 7,200 dpi", "6 botones", "Aceleración de 20 G", "Iluminación RGB"],
    specs: [["Resolución", "7,200 dpi"], ["Botones", "6"], ["Factor de forma", "Diestro"], ["Cable", "1.5 m"], ["Compatibilidad", "Windows y Linux"]],
  },

  /* ===================== TECLADOS ===================== */
  {
    id: "g915-x-tkl",
    cat: "teclados",
    brand: "Logitech G",
    name: "Logitech G915 X LIGHTSPEED TKL Blanco",
    price: 2409,
    img: "img/p139.jpg",
    badge: "Premium",
    featured: true,
    desc: "Teclado mecánico de perfil bajo sin teclado numérico, con switches GL Tactile, conexión inalámbrica LIGHTSPEED y Bluetooth, e iluminación RGB.",
    hl: ["Switches mecánicos GL Tactile", "LIGHTSPEED + Bluetooth", "Perfil bajo", "Formato TKL", "RGB LIGHTSYNC"],
    specs: [["Switch", "Logitech GL Tactile"], ["Conexión", "RF inalámbrico + Bluetooth"], ["Formato", "Tenkeyless"], ["Fuerza de acción", "45 g"], ["Actuación", "1.3 mm"], ["Idioma", "Inglés"]],
  },
  {
    id: "aw420k",
    cat: "teclados",
    brand: "Alienware",
    name: "Alienware AW420K",
    price: 2179,
    img: "img/p141.jpg",
    desc: "Teclado mecánico TKL con switches Cherry MX Red, teclas PBT de doble disparo, N-key rollover y memoria integrada.",
    hl: ["Switches Cherry MX Red", "Teclas PBT doble disparo", "100 millones de pulsaciones", "N-key rollover", "1000 Hz"],
    specs: [["Switch", "Cherry MX Red"], ["Formato", "Tenkeyless"], ["Teclas", "PBT doble disparo"], ["Sondeo", "1000 Hz"], ["Idioma", "Inglés"]],
  },
  {
    id: "defeat-gk3",
    cat: "teclados",
    brand: "Balam Rush",
    name: "Balam Rush Defeat Level GK3",
    price: 1049,
    img: "img/p131.jpg",
    badge: "Inalámbrico",
    desc: "Teclado mecánico 90 % con switches KTT Cream Yellow Pro, conexión 2.4 GHz y Bluetooth 5.1, pantalla integrada y perilla. Combinación negro y naranja.",
    hl: ["Switch KTT Cream Yellow Pro", "2.4 GHz + Bluetooth 5.1", "Formato 90 % · 100 teclas", "Español con Ñ", "Anti-ghosting"],
    specs: [["Formato", "90 % (100 teclas)"], ["Conexión", "USB + Bluetooth 5.1"], ["Sondeo", "1000 Hz"], ["Alcance", "10 m"], ["Idioma", "Español"]],
  },
  {
    id: "kbg560",
    cat: "teclados",
    brand: "Game Factor",
    name: "Game Factor KBG560",
    price: 760.09,
    old: 889,
    img: "img/p121.jpg",
    desc: "Teclado mecánico 60 % con switches Outemu Blue, cable USB-C removible y keycaps intercambiables incluidas. Ideal para torneos y LAN parties.",
    hl: ["Switches Outemu Blue", "Formato 60 %", "Keycaps extra incluidas", "Cable USB-C removible", "RGB personalizable"],
    specs: [["Switch", "Outemu Blue"], ["Formato", "60 %"], ["Idioma", "Español"], ["Material", "Metal"], ["Cable", "1.5 m USB-C"]],
  },
  {
    id: "gk990",
    cat: "teclados",
    brand: "Balam Rush",
    name: "Balam Rush LEVEL PRO GK990",
    price: 749,
    img: "img/p133.jpg",
    badge: "Inalámbrico",
    desc: "Teclado 80 % inalámbrico y alámbrico con switches Outemu Red, Bluetooth 5.0 y 50 millones de pulsaciones. Diseño gris y negro.",
    hl: ["Switch Outemu Red", "Inalámbrico + alámbrico", "Bluetooth 5.0", "Formato 80 % · 88 teclas", "Español con Ñ"],
    specs: [["Switch", "Outemu Red"], ["Formato", "80 % (88 teclas)"], ["Sondeo", "1000 Hz"], ["Cable", "1.8 m"], ["Idioma", "Español"]],
  },
  {
    id: "ornata-v3",
    cat: "teclados",
    brand: "Razer",
    name: "Razer Ornata V3",
    price: 659,
    img: "img/p123.jpg",
    desc: "Switches de membrana mecánica Razer de perfil bajo, teclas con recubrimiento UV, Razer Chroma RGB y reposamuñecas magnético. Resistente a derrames.",
    hl: ["Switches mecha-membrana", "Perfil bajo ergonómico", "Razer Chroma RGB", "Reposamuñecas magnético", "Resistente a derrames"],
    specs: [["Switch", "Membrana mecánica"], ["Formato", "Tamaño completo"], ["Sondeo", "1000 Hz"], ["Idioma", "Español"], ["Reposamuñecas", "Sí"]],
  },
  {
    id: "sorcerer-mini",
    cat: "teclados",
    brand: "XPG",
    name: "XPG SORCERER MINI",
    price: 639,
    img: "img/p117.jpg",
    desc: "Teclado mecánico 65 % compacto con switches XPG Red, RGB por tecla con 10 efectos y cable USB-C desmontable.",
    hl: ["Switch XPG Red Mechanical", "Formato 65 %", "RGB por tecla", "USB-C desmontable", "Perilla multifunción"],
    specs: [["Switch", "XPG Red"], ["Formato", "65 %"], ["Iluminación", "10 efectos por tecla"], ["Conector", "USB tipo C"], ["Idioma", "Inglés"]],
  },
  {
    id: "gladiator",
    cat: "teclados",
    brand: "Nextep",
    name: "Nextep Dragon War Gladiator",
    price: 443.74,
    old: 519,
    img: "img/p119.jpg",
    desc: "Teclado gamer semi mecánico con colores RGB de fondo intercambiables y conexión USB con terminal dorada.",
    hl: ["Semi mecánico", "Iluminación RGB", "USB con terminal dorada", "Teclado numérico"],
    specs: [["Tipo", "Semi mecánico"], ["Iluminación", "RGB"], ["Interfaz", "USB"], ["Idioma", "Inglés"]],
  },
  {
    id: "gk777",
    cat: "teclados",
    brand: "Balam Rush",
    name: "Balam Rush Dominate X Pro GK777",
    price: 419,
    img: "img/p129.jpg",
    desc: "Teclado mecánico con switch rojo, iluminación RGB, distribución en español y perilla multimedia. 98 teclas en formato compacto.",
    hl: ["Switch rojo mecánico", "RGB", "QWERTY español", "98 teclas + perilla", "1000 Hz"],
    specs: [["Switch", "Rojo"], ["Teclas", "98 + perilla"], ["Sondeo", "1000 Hz"], ["Cable", "1.5 m"], ["Idioma", "Español"]],
  },
  {
    id: "brobotix-kit",
    cat: "teclados",
    brand: "BRobotix",
    name: "Kit BRobotix 188533-2 teclado + mouse",
    price: 419,
    old: 489,
    img: "img/p135.jpg",
    badge: "Kit",
    desc: "Kit gamer de teclado tamaño completo y mouse con retroiluminación multicolor, teclas multimedia y altura ajustable.",
    hl: ["Teclado + mouse", "Retroiluminación multicolor", "Teclas multimedia", "Español"],
    specs: [["Tipo", "Membrana"], ["Formato", "Tamaño completo"], ["Idioma", "Español"], ["Cable", "1.5 m"]],
  },
  {
    id: "ckg690",
    cat: "teclados",
    brand: "Balam Rush",
    name: "Kit Balam Rush Fusion Vanguard CKG690",
    price: 409,
    img: "img/p125.jpg",
    badge: "Kit",
    desc: "Kit de teclado mecánico de 105 teclas con distribución en español y mouse óptico, iluminación RGB y 1000 Hz.",
    hl: ["Teclado mecánico + mouse óptico", "105 teclas", "QWERTY español", "RGB", "1000 Hz"],
    specs: [["Teclas", "105"], ["Sondeo", "1000 Hz"], ["Cable", "1.5 m"], ["Idioma", "Español"]],
  },
  {
    id: "gk110",
    cat: "teclados",
    brand: "MSI",
    name: "Kit MSI FORGE GK110 teclado + mouse",
    price: 409,
    img: "img/p143.jpg",
    badge: "Kit",
    desc: "Kit compacto de 97 teclas con iluminación RGB y mouse óptico de 12,800 dpi con 7 botones y 13 modos RGB.",
    hl: ["Teclado compacto de 97 teclas", "Mouse de 12,800 dpi", "7 botones en el mouse", "13 modos RGB", "QWERTY inglés"],
    specs: [["Teclas", "97"], ["Mouse", "Óptico 12,800 dpi"], ["Cable", "1.5 m"], ["Idioma", "Inglés"]],
  },
  {
    id: "vorago-kb600",
    cat: "teclados",
    brand: "Vorago",
    name: "Vorago KB-600",
    price: 279,
    img: "img/p127.jpg",
    desc: "Teclado mecánico 80 % de 88 teclas con estructura metálica, iluminación LED RGB, anti-ghosting y teclas multimedia.",
    hl: ["Mecánico", "Formato 80 % · 88 teclas", "LED RGB", "Anti-ghosting", "Estructura de metal"],
    specs: [["Formato", "80 % (88 teclas)"], ["Material", "Metal"], ["Cable", "1.6 m"], ["Consumo", "180 mA"]],
  },
  {
    id: "kg490",
    cat: "teclados",
    brand: "Balam Rush",
    name: "Balam Rush Balrak Pro KG490",
    price: 269,
    img: "img/p145.jpg",
    desc: "Teclado compacto con retroiluminación RGB, 19 teclas anti-ghosting, perilla multimedia y distribución en español.",
    hl: ["Retroiluminación RGB", "19 teclas anti-ghosting", "98 teclas + perilla", "QWERTY español"],
    specs: [["Teclas", "98 + perilla"], ["Sondeo", "125 Hz"], ["Cable", "1.5 m"], ["Idioma", "Español"]],
  },
  {
    id: "xzeal-xst201",
    cat: "teclados",
    brand: "Xzeal",
    name: "Kit Xzeal XST-201 teclado + mouse",
    price: 189,
    old: 219,
    img: "img/p87.jpg",
    badge: "Kit",
    desc: "Kit de teclado de membrana tamaño completo con retroiluminación Rainbow y 19 teclas anti-ghosting, más mouse de 6 botones a 3,200 dpi.",
    hl: ["Retroiluminación Rainbow", "19 teclas anti-ghosting", "Mouse de 6 botones", "3,200 dpi"],
    specs: [["Modelo", "XSKTALRW1B"], ["Formato", "Tamaño completo"], ["Mouse", "3,200 dpi · 6 botones"], ["Cable", "1.45 m"], ["Peso del teclado", "405 g"]],
  },
  {
    id: "brobotix-420028",
    cat: "teclados",
    brand: "BRobotix",
    name: "BRobotix 420028 RGB Tricolor",
    price: 179,
    img: "img/p137.jpg",
    desc: "Teclado gamer tamaño completo con retroiluminación tricolor azul, rojo y magenta, y diseño de plancha ergonómico.",
    hl: ["Retroiluminación tricolor", "Tamaño completo", "Teclado numérico", "Diseño ergonómico"],
    specs: [["Formato", "Tamaño completo"], ["Iluminación", "Azul / Rojo / Magenta"], ["Cable", "1.5 m"], ["Interfaz", "USB"]],
  },

  /* ===================== AUDÍFONOS ===================== */
  {
    id: "kraken-v3x",
    cat: "audio",
    brand: "Razer",
    name: "Razer Kraken V3 X",
    price: 1529,
    old: 1699,
    img: "img/p157.jpg",
    featured: true,
    desc: "Altavoces Razer TriForce de 40 mm, sonido envolvente 7.1 para audio posicional y micrófono cardioide HyperClear con cancelación de ruido.",
    hl: ["Altavoces TriForce de 40 mm", "Sonido envolvente 7.1", "Micrófono cardioide HyperClear", "Respuesta de 12–28,000 Hz"],
    specs: [["Interfaz", "USB"], ["Respuesta", "12–28,000 Hz"], ["Impedancia", "32 Ω"], ["Sensibilidad", "103 dB"], ["Cable", "2 m"]],
  },
  {
    id: "hs80",
    cat: "audio",
    brand: "Corsair",
    name: "Corsair HS80 RGB USB Blanco",
    price: 1329,
    img: "img/p159.jpg",
    desc: "Transductores de neodimio de 50 mm con rango ampliado, almohadillas de espuma viscoelástica y micrófono omnidireccional con calidad de transmisión.",
    hl: ["Transductores de 50 mm", "Respuesta de 20–40,000 Hz", "Micrófono omnidireccional", "Diadema flotante", "Iluminación RGB"],
    specs: [["Interfaz", "USB tipo A"], ["Respuesta", "20–40,000 Hz"], ["Sensibilidad", "116 dB"], ["Cable", "1.8 m"], ["Color", "Blanco"]],
  },
  {
    id: "amd-g10",
    cat: "audio",
    brand: "AMD",
    name: "AMD Royal Gaming Gear G10",
    price: 1076.44,
    img: "img/p147.jpg",
    desc: "Audífonos gamer USB con sonido envolvente 360° 7.1, luz LED multicolor y micrófono omnidireccional.",
    hl: ["Sonido envolvente 7.1", "Luz LED multicolor", "Micrófono omnidireccional", "Conexión USB"],
    specs: [["Interfaz", "USB"], ["Respuesta", "20–20,000 Hz"], ["Impedancia", "16 Ω"], ["Sensibilidad", "108 dB"], ["Cable", "2 m"]],
  },
  {
    id: "g335",
    cat: "audio",
    brand: "Logitech G",
    name: "Logitech G335 Menta",
    price: 1050.79,
    old: 1229,
    img: "img/p155.jpg",
    desc: "Ligeros y coloridos: solo 240 g, diadema de suspensión ajustable y almohadillas de espuma viscoelástica. Conexión de 3.5 mm para PC, consolas y móviles.",
    hl: ["Solo 240 g", "Diadema de suspensión", "Almohadillas viscoelásticas", "Compatible con PC, Xbox, PlayStation y Switch"],
    specs: [["Interfaz", "3.5 mm"], ["Respuesta", "20–20,000 Hz"], ["Impedancia", "36 Ω"], ["Sensibilidad", "87.5 dB SPL/mW"], ["Peso", "240 g"]],
  },
  {
    id: "precog-studio",
    cat: "audio",
    brand: "XPG",
    name: "XPG PRECOG STUDIO",
    price: 789,
    img: "img/p151.jpg",
    desc: "Audífonos gamer alámbricos con conexión USB-C y 3.5 mm, cable extraíble y control giratorio de volumen con botón de silencio.",
    hl: ["USB-C y 3.5 mm", "Cable extraíble", "Control de volumen giratorio", "Botón de silencio"],
    specs: [["Conexión", "USB tipo C + 3.5 mm"], ["Estilo", "Diadema"], ["Color", "Negro / Rojo"], ["Cable extraíble", "Sí"]],
  },
  {
    id: "nasa-hsg03",
    cat: "audio",
    brand: "TechZone",
    name: "TechZone NASA NS-HSG03",
    price: 315.49,
    old: 369,
    img: "img/p149.jpg",
    desc: "Diseño compacto y plegable en blanco con detalles azul y rojo, logo distintivo de NASA, iluminación RGB y aislamiento pasivo de ruido.",
    hl: ["Diseño oficial NASA", "Iluminación RGB", "3.5 mm y USB", "Almohadillas cómodas y ajustables"],
    specs: [["Interfaz", "3.5 mm / USB"], ["Impedancia", "32 Ω"], ["Sensibilidad", "115 dB"], ["Cable", "2 m"], ["Color", "Blanco / Azul"]],
  },
  {
    id: "arcus-300s",
    cat: "audio",
    brand: "Primus",
    name: "Primus ARCUS 300S",
    price: 299,
    img: "img/p161.jpg",
    desc: "Audífonos true wireless con estuche de carga con pantalla de batería, Bluetooth 5.0 y micrófono integrado.",
    hl: ["True wireless", "Bluetooth 5.0", "Estuche con indicador de batería", "Android e iOS"],
    specs: [["Conexión", "Bluetooth 5.0"], ["Respuesta", "20–20,000 Hz"], ["Alcance", "10 m"], ["Color", "Blanco"]],
  },
  {
    id: "hs688",
    cat: "audio",
    brand: "Balam Rush",
    name: "Balam Rush Hesix II HS688",
    price: 269,
    img: "img/p165.jpg",
    desc: "Audífonos circumaurales con drivers de 5 cm, aro RGB y micrófono tipo boom. Conexión 3.5 mm con USB para iluminación.",
    hl: ["Drivers de 5 cm", "Iluminación RGB", "Micrófono boom", "Sensibilidad de 120 dB"],
    specs: [["Conexión", "3.5 mm + USB"], ["Impedancia", "32 Ω"], ["Sensibilidad", "120 dB"], ["Cable", "2.1 m"]],
  },
  {
    id: "eagle-diamond",
    cat: "audio",
    brand: "Eagle Warrior",
    name: "Eagle Warrior Diamond",
    price: 255.64,
    old: 299,
    img: "img/p153.jpg",
    desc: "Audífonos gamer con iluminación LED y micrófono, conexión 3.5 mm y USB. Compatibles con Xbox, PS4 y PC.",
    hl: ["Iluminación LED", "Micrófono incluido", "3.5 mm y USB", "Xbox, PS4 y PC"],
    specs: [["Interfaz", "3.5 mm / USB"], ["Micrófono", "Sí"], ["Compatibilidad", "Xbox, PS4 y PC"]],
  },
  {
    id: "perfect-choice-tws",
    cat: "audio",
    brand: "Perfect Choice",
    name: "Perfect Choice True Wireless Gamer",
    price: 249,
    img: "img/p163.jpg",
    desc: "Audífonos inalámbricos intraaurales con Bluetooth 5.3, control táctil, carga USB-C y micrófono con cancelación de ruido.",
    hl: ["Bluetooth 5.3", "Control táctil", "Carga USB-C", "Micrófono con cancelación de ruido"],
    specs: [["Conexión", "Bluetooth 5.3"], ["Alcance", "10 m"], ["Conector", "USB tipo C"], ["Color", "Negro"]],
  },
];

/* =========================================================
   RESEÑAS — aparecen en movimiento en la página.
   Son textos de ejemplo: reemplázalos por reseñas reales de tus clientes.
   stars: 1 a 5
   ========================================================= */
const REVIEWS = [
  { name: "Mariana G.", city: "Guadalajara, Jal.", stars: 5, product: "iPhone 15", text: "Me atendieron súper rápido por WhatsApp, el equipo llegó impecable y con la batería en excelente estado." },
  { name: "Luis R.", city: "Monterrey, N.L.", stars: 5, product: "Nintendo Switch 2", text: "Pagué por SPEI y en dos días ya tenía la consola en casa. Todo sellado." },
  { name: "Andrea P.", city: "CDMX", stars: 5, product: "Galaxy S24 Ultra", text: "Tenía dudas por ser semi nuevo, pero parece de caja. El asesor me mandó fotos y video antes de pagar." },
  { name: "Jorge M.", city: "Puebla, Pue.", stars: 4, product: "Logitech G502 HERO", text: "Buen precio y envío rápido. La guía de rastreo me la compartieron el mismo día." },
  { name: "Daniela S.", city: "Querétaro, Qro.", stars: 5, product: "iPhone 16 Pro", text: "Muy buena experiencia. Pagué con tarjeta sin problema y me resolvieron todas mis dudas." },
  { name: "Carlos V.", city: "Tijuana, B.C.", stars: 5, product: "Xbox Series X", text: "Llegó perfecto y bien empacado. Ya es mi segunda compra con ellos." },
  { name: "Fernanda L.", city: "Mérida, Yuc.", stars: 5, product: "Galaxy A55", text: "El color lila está hermoso. Atención amable y precio mejor que en otras tiendas." },
  { name: "Ricardo T.", city: "León, Gto.", stars: 5, product: "Razer Kraken V3 X", text: "Excelente sonido y llegaron antes de lo prometido. Totalmente recomendable." },
  { name: "Sofía H.", city: "Toluca, Edo. Méx.", stars: 4, product: "iPhone 14", text: "Todo bien con mi pedido; el equipo funciona perfecto y la batería dura todo el día." },
  { name: "Miguel A.", city: "Hermosillo, Son.", stars: 5, product: "PlayStation 5", text: "Proceso muy fácil: armé el carrito, se envió por WhatsApp y en minutos ya estaba confirmado." },
];

/* =========================================================
   POLÍTICAS — se abren desde la sección "Políticas" y el pie de página.
   Ajusta plazos y condiciones a como trabajas.
   ========================================================= */
const POLICIES = [
  {
    id: "envios",
    icon: "truck",
    title: "Envíos",
    summary: "Enviamos a todo México con guía de rastreo.",
    sections: [
      ["Cobertura", "Realizamos envíos a toda la República Mexicana mediante paqueterías nacionales, con entrega a domicilio."],
      ["Tiempos de entrega", "Los pedidos se envían en 1 a 2 días hábiles después de confirmar el pago. El tránsito habitual es de 2 a 5 días hábiles según tu código postal."],
      ["Costo", "El costo de envío se calcula según tu ciudad y código postal y se confirma por WhatsApp antes de pagar."],
      ["Rastreo", "Al enviar tu pedido te compartimos el número de guía para que sigas tu paquete en todo momento."],
      ["Recepción", "Revisa el paquete al recibirlo. Si la caja llega dañada o abierta, repórtalo con la paquetería y avísanos por WhatsApp en un plazo de 24 horas."],
    ],
  },
  {
    id: "pagos",
    icon: "card",
    title: "Pagos",
    summary: "Transferencia SPEI o tarjeta de débito/crédito.",
    sections: [
      ["Métodos aceptados", "Transferencia SPEI y tarjeta de débito o crédito (Visa, Mastercard y American Express)."],
      ["Tarjeta de débito o crédito", "El pago con tarjeta de débito o crédito se hará directo con el establecimiento."],
      ["Cómo pagar", "Tu pedido se envía por WhatsApp. El asesor confirma existencias y total, y te comparte la CLABE para SPEI o un enlace de pago seguro para tarjeta."],
      ["Seguridad", "Nunca te pediremos los datos de tu tarjeta por chat ni en esta página. Los pagos con tarjeta se realizan únicamente en plataformas de pago seguras."],
      ["Confirmación", "Tu pedido queda apartado una vez que validamos el pago. Envía tu comprobante por WhatsApp para agilizar el proceso."],
      ["Facturación", "Si necesitas factura, solicítala al hacer tu pedido indicando tus datos fiscales."],
    ],
  },
  {
    id: "garantia",
    icon: "shield",
    title: "Garantía",
    summary: "Todos los productos cuentan con garantía.",
    sections: [
      ["Productos nuevos", "Los productos nuevos cuentan con la garantía del fabricante. Te apoyamos con el proceso de reclamación."],
      ["Celulares semi nuevos y outlet", "Los equipos semi nuevos y outlet cuentan con garantía de funcionamiento de 30 días a partir de la entrega."],
      ["Qué cubre", "Fallas de funcionamiento de fábrica o no reportadas al momento de la venta."],
      ["Qué no cubre", "Daños por golpes, caídas, humedad, pantallas rotas, manipulación por terceros o desgaste por uso normal."],
      ["Cómo hacerla válida", "Escríbenos por WhatsApp con tu folio de pedido, una descripción de la falla y fotos o video."],
    ],
  },
  {
    id: "devoluciones",
    icon: "refresh",
    title: "Cambios y devoluciones",
    summary: "Tienes 7 días para solicitar un cambio.",
    sections: [
      ["Plazo", "Puedes solicitar un cambio o devolución dentro de los 7 días naturales posteriores a recibir tu pedido."],
      ["Condiciones", "El producto debe estar completo, sin daños, con todos sus accesorios y empaque original. En productos sellados, el sello no debe haberse abierto, salvo por falla."],
      ["Producto con falla", "Si el producto llega con falla, cubrimos el envío de regreso y te enviamos un reemplazo o te reembolsamos."],
      ["Reembolsos", "Los reembolsos se realizan por el mismo medio de pago en un plazo de 3 a 10 días hábiles después de recibir y revisar el producto."],
      ["Excepciones", "No aplican devoluciones en códigos digitales, tarjetas de regalo ni productos dañados por mal uso."],
    ],
  },
  {
    id: "privacidad",
    icon: "lock",
    title: "Aviso de privacidad",
    summary: "Cuidamos tus datos personales.",
    sections: [
      ["Datos que recabamos", "Nombre, número de teléfono, ciudad, código postal y dirección de entrega, únicamente para procesar y enviar tu pedido."],
      ["Uso de la información", "Usamos tus datos para confirmar tu compra, coordinar el pago y el envío, y darte seguimiento o atención de garantía."],
      ["Compartir datos", "Solo compartimos los datos de entrega con la paquetería encargada de tu envío. No vendemos ni rentamos tu información."],
      ["Datos de pago", "Esta página no almacena datos de tarjetas. Los pagos se procesan en plataformas externas seguras."],
      ["Tus derechos", "Puedes solicitar el acceso, corrección o eliminación de tus datos en cualquier momento escribiéndonos por WhatsApp."],
    ],
  },
  {
    id: "terminos",
    icon: "fileText",
    title: "Términos y condiciones",
    summary: "Condiciones generales de compra.",
    sections: [
      ["Precios", "Todos los precios están en pesos mexicanos (MXN) e incluyen IVA. Pueden cambiar sin previo aviso; se respeta el precio confirmado por tu asesor."],
      ["Disponibilidad", "Las existencias se confirman por WhatsApp antes del pago. Si un producto no está disponible, te ofrecemos una alternativa o el reembolso total."],
      ["Imágenes", "Las imágenes son ilustrativas. En equipos semi nuevos y outlet puedes solicitar fotos reales antes de comprar."],
      ["Estado de los equipos", "Semi nuevo: equipo revisado en excelente estado estético. Outlet: equipo funcional que puede presentar ligeras marcas de uso."],
      ["Aceptación", "Al enviar tu pedido aceptas estas condiciones y las políticas de envío, pago, garantía y devoluciones."],
    ],
  },
];
